import type { Category, Product, FishingSpot, WeatherTideInfo, Order, FishSpecies, BoatTrip, CommunityCatch } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-rods',
    name_ar: 'قصبات وصنانير الصيد',
    name_en: 'Fishing Rods',
    slug: 'rods',
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    icon: 'Fish',
    description_ar: 'قصبات كاستينج، شاطئية، جيجينج، وترولينج من أفضل الماركات العالمية المصنوعة من الكربون الخفيف فائق القوة.',
    description_en: 'Casting, surf, jigging, and trolling rods made from high-modulus lightweight carbon.',
    sort_order: 1,
    product_count: 14,
  },
  {
    id: 'cat-reels',
    name_ar: 'مكينات وبكرات السحب',
    name_en: 'Fishing Reels',
    slug: 'reels',
    image_url: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    icon: 'Disc',
    description_ar: 'بكرات سبينينج، بيت كاستينج، وبكرات أعماق ثقيلة مقاومة للملوحة ومانعة للتآكل.',
    description_en: 'Spinning, baitcasting, and heavy offshore reels with saltwater corrosion resistance.',
    sort_order: 2,
    product_count: 12,
  },
  {
    id: 'cat-lures',
    name_ar: 'الطعوم الصناعية والميرور',
    name_en: 'Lures & Baits',
    slug: 'lures',
    image_url: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80',
    icon: 'Sparkles',
    description_ar: 'ميرور، جيجات معدنية، بوبر، طعوم سيليكون حركية تحاكي الأسماك الحقيقية لجذب أقوى المفترسات.',
    description_en: 'Metal jigs, poppers, minnows, and soft plastics engineered for realistic swimming action.',
    sort_order: 3,
    product_count: 24,
  },
  {
    id: 'cat-lines',
    name_ar: 'خيوط الصيد والليدر',
    name_en: 'Fishing Lines',
    slug: 'lines',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    icon: 'Activity',
    description_ar: 'خيوط حرير مضفورة بريد 8X و 9X، خيوط فلوروكربون غير مرئية، وخيوط نايلون مرنة.',
    description_en: '8X/9X braided lines, invisible fluorocarbon leaders, and high-tensile monofilament lines.',
    sort_order: 4,
    product_count: 10,
  },
  {
    id: 'cat-spearfishing',
    name_ar: 'معدات الغوص والصيد بالرمح',
    name_en: 'Spearfishing & Diving',
    slug: 'spearfishing',
    image_url: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&w=800&q=80',
    icon: 'Compass',
    description_ar: 'مسدسات صيد بالرمح كاربون ومطاط، نظارات غوص مفرغة، زعانف طويلة، وبدل مموهة.',
    description_en: 'Carbon spearguns, low-volume freediving masks, long blades, and camo wetsuits.',
    sort_order: 5,
    product_count: 8,
  },
  {
    id: 'cat-electronics',
    name_ar: 'أجهزة السونار والملاحة',
    name_en: 'Marine Electronics',
    slug: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    icon: 'Radio',
    description_ar: 'أجهزة كاشف الأسماك Fish Finders، بوصلات بحرية، وخرائط الأعماق GPS الذكية.',
    description_en: 'High-precision fish finders, marine GPS chartplotters, and depth transducers.',
    sort_order: 6,
    product_count: 6,
  },
  {
    id: 'cat-accessories',
    name_ar: 'حقائب وصناديق وإكسسوارات',
    name_en: 'Tackle Boxes & Gear',
    slug: 'accessories',
    image_url: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80',
    icon: 'Shield',
    description_ar: 'صناديق حفظ المعدات المقاومة للماء، كماشات صيد من التيتانيوم، شباك وموازين ديجيتال.',
    description_en: 'Waterproof tackle storage, titanium fishing pliers, lip grippers, and digital scales.',
    sort_order: 7,
    product_count: 18,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title_ar: 'قصبة شيمانو كولسنايبر XR كاستينج وجيجينج 3.05 متر',
    title_en: 'Shimano ColtSniper XR Casting & Shore Jigging Rod 3.05m',
    description_ar: 'قصبة صيد كربونية احترافية بتقنية Spiral X Core و Hi-Power X لمنحك رميات بعيدة المدى ومقاومة مذهلة لأقوى أسماك الشاطئ والتونة والكنعد.',
    description_en: 'Premium carbon shore jigging rod featuring Shimano Spiral X Core and Hi-Power X technologies for ultra-long casts and supreme fighting power.',
    price: 3450,
    original_price: 4100,
    discount_percent: 16,
    rating: 4.9,
    review_count: 38,
    stock: 15,
    category_id: 'cat-rods',
    category_slug: 'rods',
    brand: 'Shimano',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: true,
    is_best_seller: true,
    is_flash_deal: true,
    specs: {
      length: '3.05 متر (10 أقدام)',
      weight: '295 جرام',
      material: 'Spiral X Core Carbon Fiber',
      drag_power: 'قوة رمي 40-100 جرام جيج',
      action: 'سريعة (Fast Action)',
      power: 'ثقيلة جداً (Heavy / X-Heavy)',
      water_type: 'saltwater',
      fishing_type: 'كاستينج وشور جيجينج (Shore Jigging)',
      target_fish: ['تونة (Tuna)', 'كنعد / ديرك (Kingfish)', 'شروي / كراكند', 'هامور'],
    },
    tags: ['كاستينج', 'شور جيجينج', 'شيمانو', 'كربون'],
    reviews: [
      {
        id: 'rev-1',
        user_name: 'الكابتن أحمد حسني',
        rating: 5,
        date: '2026-08-20',
        comment: 'قصبة أسطورية حرفياً! الرمية فيها خرافية وتصل لمسافات لم أكن أتخيلها، مسكت بيها كنعد 8 كيلو وكانت ثابتة جداً.',
        verified: true,
      },
      {
        id: 'rev-2',
        user_name: 'محمود الصاوي',
        rating: 5,
        date: '2026-08-15',
        comment: 'خفيفة جداً في الإيد وجودة الحلقات الفوجي عالية وتتحمل الخيوط الحرير بدون أي احتكاك.',
        verified: true,
      },
    ],
  },
  {
    id: 'prod-2',
    title_ar: 'ماكينة دايوا سالتيجا 2026 هيفي ديوتي مقاس 10000',
    title_en: 'Daiwa Saltiga 10000 Heavy Duty Saltwater Reel',
    description_ar: 'قمة هندسة البكرات البحرية مع دراج بقوة 25 كجم وتروس مانعة لدخول مياه البحر Magsealed وجسم قطعة واحدة من الألومنيوم Monocoque.',
    description_en: 'Flagship saltwater spinning reel featuring Monocoque aluminum body, Magsealed bearings, and an astonishing 25kg ATD carbon drag.',
    price: 8900,
    original_price: 10200,
    discount_percent: 13,
    rating: 5.0,
    review_count: 52,
    stock: 8,
    category_id: 'cat-reels',
    category_slug: 'reels',
    brand: 'Daiwa',
    images: [
      'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: true,
    is_best_seller: true,
    specs: {
      weight: '645 جرام',
      gear_ratio: '5.8:1',
      drag_power: '25 كجم (Carbon ATD)',
      line_capacity: 'PE 5 - 400 متر / PE 6 - 300 متر',
      bearing_count: '14 + 1 Magsealed CRBB',
      material: 'MQ Aluminum Body',
      water_type: 'saltwater',
      fishing_type: 'بوبينج، جيجينج ثقيل، أعماق',
      target_fish: ['تونة عملاقة (Giant GT)', 'شراع / مارلين', 'هامور أعماق', 'عنبران'],
    },
    tags: ['دايوا', 'سالتيجا', 'سحب ثقيل', 'مقاوم للملوحة'],
    reviews: [
      {
        id: 'rev-3',
        user_name: 'عمر القحطاني',
        rating: 5,
        date: '2026-08-25',
        comment: 'أقوى ماكينة صيد نزلت السوق، سلاسة دوران لا توصف وقوة سحب كأنك بتسحب رافعة!',
        verified: true,
      },
    ],
  },
  {
    id: 'prod-3',
    title_ar: 'طعم صناعي رابالا اكس راب ماجنوم 16 سم عائم للترولينج',
    title_en: 'Rapala X-Rap Magnum 160 High Speed Trolling Lure',
    description_ar: 'طعم جري ترولينج غاطس للأعماق حتى 6 أمتار بسرعة سحب تصل إلى 13 عقدة، مصمم بألوان عاكسة للأشعة وهيكل مقوى يتحمل أقوى الأسنان الحادة.',
    description_en: 'World-renowned high-speed trolling lure dives unassisted up to 20 feet at speeds up to 13 knots with textured translucent body.',
    price: 320,
    original_price: 390,
    discount_percent: 18,
    rating: 4.8,
    review_count: 64,
    stock: 45,
    category_id: 'cat-lures',
    category_slug: 'lures',
    brand: 'Rapala',
    images: [
      'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: true,
    is_new: true,
    is_flash_deal: true,
    specs: {
      length: '16 سم',
      weight: '77 جرام',
      diving_depth: '6 أمتار (20 قدم)',
      hook_size: 'خطافات VMC 4X بيريستيل مقاس 4/0',
      water_type: 'saltwater',
      fishing_type: 'ترولينج وجري بالقارب (Trolling)',
      target_fish: ['باراكودا / عقام', 'كنعد / واهو', 'تونة صفراء الزعانف', 'دراك'],
    },
    tags: ['رابالا', 'ترولينج', 'طعم غاطس', 'أكس راب'],
  },
  {
    id: 'prod-4',
    title_ar: 'خيط حرير دايوا جيه بريد جراند 8X ياباني أصلي 300 متر',
    title_en: 'Daiwa J-Braid Grand 8X Japanese Braided Line 300m',
    description_ar: 'خيط صيد ياباني مضفور من 8 ألياف IZANAS فائقة النعومة ومقاومة للاحتكاك بالصخور والشعب المرجانية مع مقاومة تمدد صفرية.',
    description_en: 'Engineered with cutting-edge IZANAS fibers for exceptional knot strength and ultra-smooth line guide flow.',
    price: 490,
    original_price: 580,
    discount_percent: 15,
    rating: 4.9,
    review_count: 85,
    stock: 60,
    category_id: 'cat-lines',
    category_slug: 'lines',
    brand: 'Daiwa',
    images: [
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: false,
    is_best_seller: true,
    specs: {
      length: '300 متر',
      material: 'IZANAS Ultra PE 8 Strands',
      drag_power: 'قوة تحمل 50 باوند (PE 3.0)',
      water_type: 'both',
      fishing_type: 'كاستينج، جيجينج، تشخيط',
      target_fish: ['جميع أنواع الأسماك البحرية والنهرية'],
    },
    tags: ['حرير', 'دايوا', '8X', 'ياباني'],
  },
  {
    id: 'prod-5',
    title_ar: 'مسدس غوص وصيد كربون روب ألين تونة 110 سم المزدوج',
    title_en: 'Rob Allen Tuna Carbon Speargun 110cm Double Band',
    description_ar: 'المسدس الأقوى عالمياً في صيد الأعماق بالرمح مصنوع من ألياف الكربون الصلب مع مطاطين بقوة 16 ملم وسهم ستانلس ستيل مطروق بالحرارة.',
    description_en: 'Aircraft-grade carbon barrel speargun rigged with dual 16mm bands and high-tensile spring steel shaft for maximum penetration.',
    price: 5200,
    original_price: 5900,
    discount_percent: 12,
    rating: 4.9,
    review_count: 27,
    stock: 10,
    category_id: 'cat-spearfishing',
    category_slug: 'spearfishing',
    brand: 'Rob Allen',
    images: [
      'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: true,
    is_new: false,
    specs: {
      length: '110 سم',
      material: 'Solid Core Carbon Tube',
      power: '2 مطاط 16 ملم مع لجام داينيما',
      hook_size: 'سهم 7.5 ملم ستيل مهدرج',
      water_type: 'saltwater',
      fishing_type: 'صيد بالرمح وغوص حر (Spearfishing)',
      target_fish: ['تونة', 'هامور صخري', 'ديرك', 'ناجل وكشر'],
    },
    tags: ['غوص', 'مسدس صيد', 'كربون', 'روب ألين'],
  },
  {
    id: 'prod-6',
    title_ar: 'جهاز جارمن سترايكر كاست سونار لاسلكي بكاشف أسماك GPS',
    title_en: 'Garmin Striker Cast Wireless Fishfinder Sonar with GPS',
    description_ar: 'سونار لاسلكي ذكي يتم ربطه بهاتفك المحمول عبر البلوتوث والواي فاي مع رسم خرائط للأعماق بدقة متناهية وإظهار تجمعات الأسماك بالحرارة والعمق.',
    description_en: 'Castable sonar transforms smartphones into fishfinders with built-in GPS Quickdraw contours and crisp fish arches.',
    price: 3600,
    original_price: 4200,
    discount_percent: 14,
    rating: 4.7,
    review_count: 41,
    stock: 18,
    category_id: 'cat-electronics',
    category_slug: 'electronics',
    brand: 'Garmin',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: true,
    is_best_seller: false,
    specs: {
      weight: '75 جرام',
      diving_depth: 'يكشف حتى عمق 45 متراً',
      power: 'بطارية تدوم أكثر من 10 ساعات شحن سريع',
      material: 'هيكل مقاوم للماء والغمر IPX7',
      water_type: 'both',
      fishing_type: 'صيد شاطئي، قوارب كاياك، بحيرات وأنهار',
      target_fish: ['تحديد مواقع كافة الأسماك وهياكل القاع'],
    },
    tags: ['سونار', 'جارمن', 'كاشف أسماك', 'GPS'],
  },
  {
    id: 'prod-7',
    title_ar: 'ماكينة بين سلامر IV سبيشال إيديشن مقاس 6500 محكمة الغلق',
    title_en: 'Penn Slammer IV 6500 High-Speed Sealed Saltwater Reel',
    description_ar: 'الماكينة الأمريكية الأسطورية المقاومة للماء بمعيار IPX6 بالكامل ونظام سحب Dura-Drag من ألياف الكربون مع تروس نحاسية مصبوبة باستخدام CNC.',
    description_en: 'Sealed IPX6 body and spool design with CNC gear technology and impenetrable Dura-Drag system for ultimate harsh sea battles.',
    price: 4650,
    original_price: 5300,
    discount_percent: 12,
    rating: 4.9,
    review_count: 49,
    stock: 14,
    category_id: 'cat-reels',
    category_slug: 'reels',
    brand: 'Penn',
    images: [
      'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: true,
    is_flash_deal: true,
    specs: {
      weight: '687 جرام',
      gear_ratio: '6.2:1',
      drag_power: '18 كجم (Penn Dura-Drag)',
      line_capacity: 'PE 4 - 350 متر',
      bearing_count: '8+1 محامل ستانلس محكمة IPX6',
      material: 'Full Metal Body',
      water_type: 'saltwater',
      fishing_type: 'شور كاستينج، لايت جيجينج، ترولينج خفيف',
      target_fish: ['شروي', 'بياض', 'كنعد', 'عقام'],
    },
    tags: ['بين', 'سلامر', 'أمريكي', 'مقاوم للماء'],
  },
  {
    id: 'prod-8',
    title_ar: 'طقم جيجات مضيئة سلو وسريع 5 قطع بأوزان متنوعة مع هوكات تيتانيوم',
    title_en: 'SeaPro Glow Jigging Lure Set (5 Pcs) with Assist Hooks',
    description_ar: 'مجموعة جيجات صيد بحرية بألوان فسفورية مضيئة في الظلام (Glow UV) مزودة بأسلاك حماية وهوكات مزدوجة يابانية حادة لصيد القاع والعمود المائي.',
    description_en: 'Premium glow-in-the-dark vertical and slow pitch jig set equipped with twin razor-sharp assist hooks and flash tinsel.',
    price: 540,
    original_price: 690,
    discount_percent: 22,
    rating: 4.8,
    review_count: 73,
    stock: 50,
    category_id: 'cat-lures',
    category_slug: 'lures',
    brand: 'SeaPro',
    images: [
      'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: false,
    is_best_seller: true,
    is_new: true,
    specs: {
      weight: 'أوزان: 40g, 60g, 80g, 100g, 150g',
      hook_size: 'هوكات مزدوجة BKK 3/0 و 4/0 مع ريش عاكس',
      material: 'رصاص مقسى مع طلاء إيبوكسي مقاوم للصدمات',
      water_type: 'saltwater',
      fishing_type: 'سلو جيجينج، فاست جيجينج، لايت جيج',
      target_fish: ['هامور', 'ناجل', 'شطف', 'شعور', 'بياض'],
    },
    tags: ['جيجات', 'سلو جيج', 'مضيء', 'هوكات BKK'],
  },
  {
    id: 'prod-9',
    title_ar: 'صندوق عدة صيد مي هو ياباني متكامل متعدد الطبقات المقاوم للماء',
    title_en: 'Meiho Versus Waterproof Multi-Compartment Tackle Box',
    description_ar: 'صندوق حفظ وتنظيم معدات الصيد من شركة ميهو اليابانية، مصنوع من بوليمر فائق التحمل للصدمات ومقاوم للملوحة مع فواصل مرنة قابلة للتعديل.',
    description_en: 'Heavy-duty Japanese tackle system with customizable interior dividers, watertight gasket seal, and reinforced lid that doubles as a seat.',
    price: 890,
    original_price: 1100,
    discount_percent: 19,
    rating: 4.9,
    review_count: 36,
    stock: 22,
    category_id: 'cat-accessories',
    category_slug: 'accessories',
    brand: 'Meiho',
    images: [
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: false,
    is_new: true,
    specs: {
      weight: '2.1 كجم',
      material: 'High-Impact Copolymer Polypropylene',
      water_type: 'both',
      fishing_type: 'جميع رحلات الصيد بالقارب والشاطئ',
      target_fish: ['حفظ وتنظيم كافة الطعوم والخطافات والخيوط'],
    },
    tags: ['صندوق عدة', 'ميهو', 'ياباني', 'مقاوم للصدمات'],
  },
  {
    id: 'prod-10',
    title_ar: 'قصبة دايوا ميجابيت شاطئية سيرف 4.5 متر كاربون ألترا لونج',
    title_en: 'Daiwa MegaBit Surfcasting Long Distance Rod 4.5m',
    description_ar: 'قصبة صيد سيرف كاستينج شاطئية ذات مدى رمي طويل جداً مصممة لاختراق التيارات والأمواج العالية وصيد أسماك الشواطئ الرملية والصخرية.',
    description_en: 'High-performance telescopic surfcasting rod built for extreme casting distances from sandy beaches and rocky shorelines.',
    price: 2150,
    original_price: 2600,
    discount_percent: 17,
    rating: 4.7,
    review_count: 29,
    stock: 19,
    category_id: 'cat-rods',
    category_slug: 'rods',
    brand: 'Daiwa',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    ],
    is_featured: false,
    is_best_seller: false,
    specs: {
      length: '4.50 متر (15 قدم)',
      weight: '430 جرام',
      material: 'HVF High Volume Fiber Carbon',
      drag_power: 'قوة رمي رصاص 100-250 جرام',
      action: 'قوية وسريعة (Fast Progressive)',
      water_type: 'saltwater',
      fishing_type: 'سيرف كاستينج شاطئي (Surfcasting)',
      target_fish: ['دنيس', 'قاروص / سي باس', 'وقار', 'لوت'],
    },
    tags: ['شاطئي', 'سيرف', 'دايوا', 'رميات بعيدة'],
  },
];

export const INITIAL_FISH_SPECIES: FishSpecies[] = [
  {
    id: 'fish-1',
    name_ar: 'التونة ذات الزعانف الصفراء (Yellowfin Tuna)',
    name_en: 'Yellowfin Tuna',
    scientific_name: 'Thunnus albacares',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    habitat_ar: 'المياه العميقة والمحيط المفتوح، حول الجزر والحيود المرجانية.',
    habitat_en: 'Deep pelagic offshore waters, drop-offs and currents.',
    water_type: 'saltwater',
    best_season_ar: 'أبريل إلى أكتوبر (قمة النشاط في الصيف والخريف)',
    best_season_en: 'April to October',
    avg_weight_kg: '15 - 80 كجم',
    depth_range: '10 - 150 متر',
    preferred_lures_ar: ['بوبرات عائمة (Poppers)', 'طعوم جري سريعة (X-Rap)', 'جيجات معدنية عمودية'],
    preferred_lures_en: ['Topwater Poppers', 'High-Speed Trolling Plugs', 'Vertical Speed Jigs'],
    technique_ar: 'بوبينج على السطح، ترولينج عالي السرعة 9-12 عقدة، فاست جيجينج.',
    technique_en: 'Topwater Popping, High-speed Trolling, Fast Vertical Jigging.',
    description_ar: 'واحدة من أسرع وأقوى الأسماك المفترسة في البحر الأحمر. تتطلب سنارة كربونية متينة جداً وماكينة سحب بدراج لا يقل عن 18 كجم مع خيوط PE 5-8.',
    description_en: 'Extremely powerful fighter requiring high drag reels and heavy jigging/popping carbon blanks.',
    recommended_category: 'rods',
  },
  {
    id: 'fish-2',
    name_ar: 'الناجل الملكي / كورال تراوت (Coral Trout)',
    name_en: 'Coral Trout (Najel)',
    scientific_name: 'Plectropomus pessuliferus',
    image: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80',
    habitat_ar: 'الشعاب المرجانية العميقة والمنحدرات الصخرية في البحر الأحمر.',
    habitat_en: 'Coral reef drop-offs and rocky pinnacles.',
    water_type: 'saltwater',
    best_season_ar: 'سبتمبر إلى مايو (الربيع والخريف)',
    best_season_en: 'September to May',
    avg_weight_kg: '3 - 18 كجم',
    depth_range: '20 - 70 متر',
    preferred_lures_ar: ['سلو جيج فسفوري (Glow Slow Jigs)', 'طعوم سيليكون بألوان الجمبري', 'ميرور غاطس'],
    preferred_lures_en: ['Glow Slow Pitch Jigs', 'Soft Plastics', 'Deep Minnows'],
    technique_ar: 'سلو بيتش جيجينج (Slow Pitch Jigging)، وتسقيط الطعوم الحية.',
    technique_en: 'Slow Pitch Jigging and bottom drifting.',
    description_ar: 'ملك الأسماك في البحر الأحمر بلا منازع من حيث المذاق والقيمة. يهاجم الجيجات بالقرب من القاع بحركات سريعة ومباغتة تتطلب رد فعل فوري لمنعه من الدخول في الشعب المرجانية.',
    description_en: 'Prized Red Sea trophy fish known for aggressive bottom strikes and delicate delicious meat.',
    recommended_category: 'lures',
  },
  {
    id: 'fish-3',
    name_ar: 'الكنعد / الديرك الملكي (King Mackerel)',
    name_en: 'King Mackerel (Kingfish / Dairak)',
    scientific_name: 'Scomberomorus commerson',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    habitat_ar: 'المياه الساحلية المفتوحة وحول المنارات والممرات البحرية.',
    habitat_en: 'Coastal pelagic waters and current lines.',
    water_type: 'saltwater',
    best_season_ar: 'أكتوبر إلى أبريل (موسم الشتاء والربيع)',
    best_season_en: 'October to April',
    avg_weight_kg: '5 - 30 كجم',
    depth_range: '0 - 40 متر',
    preferred_lures_ar: ['طعوم ترولينج ذات لسان طويل', 'كاستينج سبون معدني', 'طعوم حية (سردين/باغة)'],
    preferred_lures_en: ['Deep Diver Plugs', 'Casting Spoons', 'Live Bait'],
    technique_ar: 'ترولينج بسرعة 6-8 عقدة، شور كاستينج بالملاعق المعدنية من على الصخور والشواطئ العميقة.',
    technique_en: 'Trolling and Shore Casting with metal lures.',
    description_ar: 'سمكة ذات أسنان حادة مثل شفرات الحلاقة وسرعة انطلاق خارقة تتجاوز 70 كم/ساعة. يجب دائماً استخدام ليدر سلك معدني (Wire Leader) لمنع قطع الخيط.',
    description_en: 'Razor-sharp teeth predator requiring wire leaders and long distance high-speed lures.',
    recommended_category: 'reels',
  },
  {
    id: 'fish-4',
    name_ar: 'القاروص الأوروبي / سي باس (European Sea Bass)',
    name_en: 'European Sea Bass (قاروص)',
    scientific_name: 'Dicentrarchus labrax',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    habitat_ar: 'البحر المتوسط، مصبات الأنهار، حواجز الأمواج، والشواطئ الرملية والصخرية.',
    habitat_en: 'Mediterranean surf zones, estuaries, and rocky points.',
    water_type: 'both',
    best_season_ar: 'أكتوبر إلى يناير (الخريف وبداية الشتاء)',
    best_season_en: 'October to January',
    avg_weight_kg: '1.5 - 9 كجم',
    depth_range: '0.5 - 15 متر',
    preferred_lures_ar: ['طعوم كاستينج عائمة (Minnow 12-14cm)', 'سوفت بيت سيليكون', 'طعوم توب ووتر'],
    preferred_lures_en: ['Floating Minnows', 'Soft Swimbaits', 'Topwater Walkers'],
    technique_ar: 'لايت كاستينج مع قصبات سريعة 2.7 متر وخيوط فلوروكربون خفية.',
    technique_en: 'Light spinning with sensitive carbon rods and fluorocarbon leader.',
    description_ar: 'سمكة ذكية ومحبة للتيارات والأمواج الرغوية المتكسرة. تعتمد على التخفي وتتطلب دقة متناهية في رمي الطعوم وسحبها بطريقة انسيابية.',
    description_en: 'Cunning predator favoring turbulent surf zones and white water foamy breaks.',
    recommended_category: 'rods',
  },
];

export const INITIAL_BOAT_TRIPS: BoatTrip[] = [
  {
    id: 'trip-1',
    title_ar: 'رحلة صيد أعماق وترولينج في جزر تيران ورأس محمد',
    title_en: 'Red Sea Deep Offshore & Jigging Safari (Ras Mohammed & Tiran)',
    location_ar: 'شرم الشيخ - البحر الأحمر',
    location_en: 'Sharm El Sheikh - Red Sea',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    duration: 'يوم كامل (8 ساعات) 06:00 ص - 02:00 م',
    max_anglers: 6,
    price_per_person: 1450,
    private_boat_price: 7500,
    includes_gear: true,
    includes_food: true,
    target_species: ['تونة صفراء', 'ناجل', 'كنعد', 'هامور أعماق'],
    rating: 5.0,
    reviews_count: 34,
    departure_time: '06:00 صباحاً',
    description_ar: 'رحلة صيد بحرية فاخرة على يخت صيد مجهز بأحدث أجهزة السونار GPS وأحواض الطعم الحي مع كابتن صيد محترف ومساعدين لتجهيز الخيوط والجيجات.',
    description_en: 'Premium big game fishing charter equipped with dual Garmin sonar, live wells, and tournament gear.',
  },
  {
    id: 'trip-2',
    title_ar: 'رحلة صيد كاستينج وتسقيط في خليج السويس والزعفرانة',
    title_en: 'Suez Gulf Bottom Fishing & Casting Adventure',
    location_ar: 'بورتوفيق - السويس',
    location_en: 'Port Tawfiq - Suez',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    duration: 'نصف يوم (6 ساعات)',
    max_anglers: 5,
    price_per_person: 850,
    private_boat_price: 3800,
    includes_gear: true,
    includes_food: false,
    target_species: ['شروي', 'دراك', 'شعور', 'بياض صخري'],
    rating: 4.8,
    reviews_count: 22,
    departure_time: '05:30 صباحاً أو 01:00 ظهراً',
    description_ar: 'تجربة صيد سريعة وممتعة في أفضل نقاط صيد خليج السويس بالقرب من الشعب والجزر المغمورة.',
    description_en: 'Thrilling half-day trip targeting bottom and pelagic species in the rich Gulf of Suez.',
  },
  {
    id: 'trip-3',
    title_ar: 'رحلة صيد قاروص ودنيس شاطئية وبحرية بالإسكندرية',
    title_en: 'Alexandria Mediterranean Sea Bass & Bream Expedition',
    location_ar: 'الميناء الشرقي - الإسكندرية',
    location_en: 'Eastern Harbour - Alexandria',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    duration: '5 ساعات صباحية أو ليلية',
    max_anglers: 4,
    price_per_person: 650,
    private_boat_price: 2400,
    includes_gear: true,
    includes_food: true,
    target_species: ['قاروص', 'دنيس حبة كبيرة', 'لوت', 'مرجان'],
    rating: 4.9,
    reviews_count: 19,
    departure_time: '05:00 ص أو 06:00 م (ليلي)',
    description_ar: 'رحلة مخصصة لعشاق صيد البحر المتوسط بالطعوم الحية والكاستينج الخفيف حول القلاع والجزر الصخرية.',
    description_en: 'Specialized Mediterranean trip for sea bass and bream casting along historical reefs.',
  },
];

export const INITIAL_COMMUNITY_CATCHES: CommunityCatch[] = [
  {
    id: 'catch-1',
    angler_name: 'الكابتن أحمد حسني',
    fish_species: 'تونة زعانف صفراء (Yellowfin Tuna)',
    weight_kg: 34.5,
    location: 'رأس محمد - جنوب سيناء',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    tackle_used: 'قصبة شيمانو كولسنايبر XR + ماكينة دايوا سالتيجا 10000 + خيط حرير دايوا 8X',
    date: '2026-08-28',
    likes_count: 142,
  },
  {
    id: 'catch-2',
    angler_name: 'محمود الصاوي',
    fish_species: 'ناجل ملكي (Coral Trout)',
    weight_kg: 9.8,
    location: 'الزعفرانة - البحر الأحمر',
    image: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80',
    tackle_used: 'طقم جيجات مضيئة سلو جيج 120g + ماكينة بين سلامر IV',
    date: '2026-08-24',
    likes_count: 98,
  },
  {
    id: 'catch-3',
    angler_name: 'عمر القحطاني',
    fish_species: 'كنعد / ديرك (King Mackerel)',
    weight_kg: 18.2,
    location: 'جزر فرسان - جازان',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    tackle_used: 'طعم رابالا اكس راب ماجنوم 16 سم عائم للترولينج',
    date: '2026-08-19',
    likes_count: 115,
  },
];

export const INITIAL_SPOTS: FishingSpot[] = [
  {
    id: 'spot-1',
    title_ar: 'جزيرة تيران ورأس محمد (البحر الأحمر)',
    title_en: 'Tiran Island & Ras Mohammed (Red Sea)',
    location_ar: 'جنوب سيناء - شرم الشيخ',
    location_en: 'South Sinai - Sharm El Sheikh',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    best_season_ar: 'أكتوبر إلى مايو (الخريف والربيع)',
    best_season_en: 'October to May (Autumn & Spring)',
    target_species_ar: ['تونة صفراء', 'ناجل ملكي', 'ديرك / كنعد', 'شروي / كراكند'],
    target_species_en: ['Yellowfin Tuna', 'Coral Trout', 'King Mackerel', 'Giant Trevally'],
    recommended_gear_ar: 'قصبات جيجينج ثقيلة 200g، ماكينات سحب 8000-10000، خيوط حرير PE 5-6',
    recommended_gear_en: 'Heavy jigging rods 200g+, 8000-10000 reels, PE 5-6 braid',
    depth: '30 - 120 متر',
    difficulty: 'محترف',
  },
  {
    id: 'spot-2',
    title_ar: 'شواطئ وجزر فرسان (البحر الأحمر الجنوبي)',
    title_en: 'Farasan Islands Archipelago',
    location_ar: 'جازان - المملكة العربية السعودية',
    location_en: 'Jazan - Saudi Arabia',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    rating: 5.0,
    best_season_ar: 'نوفمبر إلى أبريل',
    best_season_en: 'November to April',
    target_species_ar: ['هامور عربي', 'شعور', 'بياض', 'عقام / باراكودا'],
    target_species_en: ['Grouper', 'Emperor', 'Trevally', 'Barracuda'],
    recommended_gear_ar: 'شور كاستينج، سلو جيجينج، وبوبرات عائمة',
    recommended_gear_en: 'Shore casting, slow jigging, floating poppers',
    depth: '15 - 60 متر',
    difficulty: 'متوسط',
  },
  {
    id: 'spot-3',
    title_ar: 'رأس الحكمة وخليج مطروح (البحر المتوسط)',
    title_en: 'Ras El Hekma & Matrouh Bay (Mediterranean)',
    location_ar: 'الساحل الشمالي - مصر',
    location_en: 'North Coast - Egypt',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    best_season_ar: 'أغسطس إلى ديسمبر',
    best_season_en: 'August to December',
    target_species_ar: ['قاروص (Sea Bass)', 'دنيس حبة كبيرة', 'لوت صخري', 'مرجان'],
    target_species_en: ['European Sea Bass', 'Gilt-head Bream', 'Meagre', 'Red Seabream'],
    recommended_gear_ar: 'قصبات سيرف 4.2 متر، خيوط نايلون 0.35، طعوم حية ودود قراص',
    recommended_gear_en: '4.2m surf rods, 0.35 mono line, live bait',
    depth: '5 - 25 متر',
    difficulty: 'مبتدئ',
  },
];

export const MOCK_WEATHER_DATA: WeatherTideInfo = {
  location: 'البحر الأحمر - خليج السويس والعقبة',
  temperature: 28,
  feels_like: 29,
  condition: 'Clear Sky / Ideal Sea Conditions',
  condition_ar: 'سماء صافية / بحر هادئ مناسب للصيد',
  wind_speed_knots: 11,
  wind_direction: 'شمالي غربي (NW)',
  wave_height_meters: 0.6,
  tide_state: 'مد صاعد (Rising)',
  moon_phase: 'First Quarter (هلال متزايد)',
  moon_phase_ar: 'تربيع أول (نشاط عالي للأسماك)',
  fishing_index: 'ممتاز 🎣🎣🎣',
  best_time: '05:30 ص - 08:30 ص | 04:45 م - 07:15 م',
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'SP-98421',
    customer_name: 'أحمد محمود التميمي',
    customer_email: 'ahmed.tamimi@example.com',
    customer_phone: '+966 55 123 4567',
    shipping_address: 'حي الشاطئ، شارع الأمير سلطان، مبنى 44',
    city: 'جدة',
    payment_method: 'card',
    payment_status: 'paid',
    status: 'shipped',
    items: [
      {
        product_id: 'prod-1',
        title_ar: 'قصبة شيمانو كولسنايبر XR كاستينج',
        title_en: 'Shimano ColtSniper XR Casting Rod',
        price: 3450,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
      },
      {
        product_id: 'prod-4',
        title_ar: 'خيط حرير دايوا جيه بريد جراند 8X',
        title_en: 'Daiwa J-Braid Grand 8X',
        price: 490,
        quantity: 2,
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 4430,
    shipping_cost: 0,
    discount: 100,
    total: 4330,
    created_at: '2026-08-30T14:20:00Z',
  },
  {
    id: 'ord-1002',
    order_number: 'SP-98422',
    customer_name: 'كابتن طارق عبد العزيز',
    customer_email: 'tarek.angler@example.com',
    customer_phone: '+20 100 987 6543',
    shipping_address: 'العجمي، شارع البيطاش الرئيسي، الإسكندرية',
    city: 'الإسكندرية',
    payment_method: 'cod',
    payment_status: 'pending',
    status: 'processing',
    items: [
      {
        product_id: 'prod-3',
        title_ar: 'طعم صناعي رابالا اكس راب ماجنوم 16 سم',
        title_en: 'Rapala X-Rap Magnum 160 Lure',
        price: 320,
        quantity: 3,
        image: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 960,
    shipping_cost: 50,
    discount: 0,
    total: 1010,
    created_at: '2026-08-31T08:15:00Z',
  },
];
